//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GoTo.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GoToParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IGoToListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoToParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] GoToParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoToParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] GoToParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoToParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] GoToParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoToParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] GoToParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoToParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] GoToParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoToParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] GoToParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoToParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] GoToParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoToParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] GoToParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoToParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] GoToParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoToParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] GoToParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GoToParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar([NotNull] GoToParser.VarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GoToParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar([NotNull] GoToParser.VarContext context);
}
