// Scenario definitions for testing .github/workflows/agent-reviewer.md via
// `gh aw trial` (see .github/tests/agent-reviewer/run.js).
//
// Each scenario is a sequence of "turns" executed against the same GitHub
// issue + PR:
//   - The first turn creates the issue and PR (title/body/initialLabels).
//   - Later turns optionally post a comment on the PR before re-running the
//     trial against the same PR.
// Every turn has an `expect` block describing the safe outputs the reviewer
// must produce for that turn.

const clearIssueBody = [
  'We need a "Copy to clipboard" button on each image card in the gallery.',
  "",
  "- Add a button overlay on each thumbnail in src/components/ImageGallery.tsx.",
  "- Clicking it copies the image's data URL to the clipboard using the",
  "  navigator.clipboard.writeText API.",
  "- Show a small 'Copied!' tooltip for 2 seconds after a successful copy.",
  "",
  "Definition of Done:",
  "- Button appears on hover over each gallery thumbnail.",
  "- Clicking it copies the correct image data URL.",
  "- A 'Copied!' tooltip appears and disappears after ~2 seconds.",
  "- npm run build and npm run lint pass.",
].join("\n");

const vagueIssueBody = [
  "Refactor the image generation module.",
  "",
  "Make it cleaner and faster.",
].join("\n");

module.exports = [
  {
    name: "pr-approved-and-merged",
    turns: [
      {
        title: "Add copy-to-clipboard button to gallery images",
        body: clearIssueBody,
        initialLabels: ["in-review"],
        commitFiles: [
          {
            path: "src/components/CopyButton.tsx",
            content: [
              '"use client";',
              "",
              "import { useCallback, useState } from \"react\";",
              "",
              "interface CopyButtonProps {",
              "  dataUrl: string;",
              "}",
              "",
              "export default function CopyButton({ dataUrl }: CopyButtonProps) {",
              "  const [copied, setCopied] = useState(false);",
              "",
              "  const handleCopy = useCallback(() => {",
              "    navigator.clipboard.writeText(dataUrl).then(() => {",
              "      setCopied(true);",
              "      setTimeout(() => setCopied(false), 2000);",
              "    });",
              "  }, [dataUrl]);",
              "",
              "  return (",
              "    <button",
              '      className="absolute inset-0 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity bg-black/40"',
              '      onClick={handleCopy}',
              '      aria-label="Copy image to clipboard"',
              "    >",
              "      {copied ? (",
              '        <span className="text-white text-sm">Copied!</span>',
              "      ) : (",
              '        <span className="text-white text-sm">Copy</span>',
              "      )}",
              "    </button>",
              "  );",
              "}",
            ].join("\n"),
            message: "Add CopyButton component for gallery images",
          },
          {
            path: "src/components/ImageGallery.tsx",
            content: [
              '"use client";',
              "",
              "import { useState } from \"react\";",
              "import type { GeneratedImage } from \"@/lib/types\";",
              "import { embedPngMetadata, isPng } from \"@/lib/png-metadata\";",
              "import CopyButton from \"./CopyButton\";",
              "",
              "interface Props {",
              "  images: GeneratedImage[];",
              "  onUseAsReference: (image: GeneratedImage) => void;",
              "}",
              "",
              "export default function ImageGallery({ images, onUseAsReference }: Props) {",
              "  const [expandedMeta, setExpandedMeta] = useState<number | null>(null);",
              "  const [saving, setSaving] = useState<number | null>(null);",
              "",
              "  if (!images.length) return null;",
              "",
              "  function handleView(url: string) {",
              "    window.open(url, \"_blank\", \"noopener,noreferrer\");",
              "  }",
              "",
              "  async function handleSave(img: GeneratedImage, idx: number) {",
              "    setSaving(idx);",
              "    try {",
              "      const response = await fetch(img.url);",
              "      const buffer = await response.arrayBuffer();",
              "",
              "      const now = new Date();",
              "      const pad = (n: number) => String(n).padStart(2, \"0\");",
              "      const baseName = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}_${pad(now.getHours())}-${pad(now.getMinutes())}-${pad(now.getSeconds())}`;",
              "",
              "      let blob: Blob;",
              "      let fileName: string;",
              "",
              "      if (isPng(buffer)) {",
              "        const withMeta = embedPngMetadata(buffer, img.metadata);",
              "        blob = new Blob([withMeta], { type: \"image/png\" });",
              "        fileName = `${baseName}.png`;",
              "      } else {",
              "        blob = new Blob([buffer]);",
              "        fileName = `${baseName}.img`;",
              "        const jsonBlob = new Blob(",
              "          [JSON.stringify(img.metadata, null, 2)],",
              "          { type: \"application/json\" },",
              "        );",
              "        const jsonUrl = URL.createObjectURL(jsonBlob);",
              "        const jsonA = document.createElement(\"a\");",
              "        jsonA.href = jsonUrl;",
              "        jsonA.download = `${baseName}.json`;",
              "        document.body.appendChild(jsonA);",
              "        jsonA.click();",
              "        document.body.removeChild(jsonA);",
              "        URL.revokeObjectURL(jsonUrl);",
              "      }",
              "",
              "      const url = URL.createObjectURL(blob);",
              "      const a = document.createElement(\"a\");",
              "      a.href = url;",
              "      a.download = fileName;",
              "      document.body.appendChild(a);",
              "      a.click();",
              "      document.body.removeChild(a);",
              "      URL.revokeObjectURL(url);",
              "    } finally {",
              "      setSaving(null);",
              "    }",
              "  }",
              "",
              "  function toggleMeta(idx: number) {",
              "    setExpandedMeta((prev) => (prev === idx ? null : idx));",
              "  }",
              "",
              "  function handleCopyJson(metadata: GeneratedImage[\"metadata\"]) {",
              "    navigator.clipboard.writeText(JSON.stringify(metadata, null, 2));",
              "  }",
              "",
              "  return (",
              '    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">',
              "      {images.map((img, i) => (",
              "        <div",
              "          key={`${img.url}-${i}`}",
              '          className="bg-card border border-border rounded-lg overflow-hidden"',
              "        >",
              '          <div className="relative">',
              "            <img",
              "              src={img.url}",
              "              alt={`Generated ${i + 1}`}",
              '              className="w-full aspect-square object-cover"',
              "            />",
              '            <CopyButton dataUrl={img.url} />',
              "          </div>",
              '          <div className="p-2 flex gap-2 flex-wrap">',
              "            <button",
              "              onClick={() => handleView(img.url)}",
              '              className="text-xs px-3 py-1 rounded bg-border hover:bg-border-hover transition-colors"',
              "            >",
              "              View",
              "            </button>",
              "            <button",
              "              onClick={() => handleSave(img, i)}",
              "              disabled={saving === i}",
              '              className="text-xs px-3 py-1 rounded bg-border hover:bg-border-hover transition-colors disabled:opacity-50"',
              "            >",
              "              {saving === i ? \"Saving...\" : \"Save\"}",
              "            </button>",
              "            <button",
              "              onClick={() => toggleMeta(i)}",
              "              className={`text-xs px-3 py-1 rounded transition-colors ${",
              "                expandedMeta === i",
              "                  ? \"bg-accent text-white\"",
              '                  : "bg-border hover:bg-border-hover"',
              "              }`}",
              "            >",
              "              Metadata",
              "            </button>",
              "            <button",
              "              onClick={() => onUseAsReference(img)}",
              '              className="text-xs px-3 py-1 rounded bg-accent hover:bg-accent-hover text-white transition-colors"',
              "            >",
              "              Use as Reference",
              "            </button>",
              "          </div>",
              "          {expandedMeta === i && (",
              '            <div className="border-t border-border p-3 bg-background/50">',
              '              <dl className="text-xs space-y-1">',
              "                {Object.entries(img.metadata).map(([key, value]) => (",
              '                  <div key={key} className="flex gap-2">',
              '                    <dt className="text-muted font-medium min-w-[80px] shrink-0">',
              "                      {key}",
              "                    </dt>",
              '                    <dd className="text-foreground/90 break-all">',
              "                      {Array.isArray(value)",
              "                        ? value.join(\", \") || \"(none)\"",
              '                        : String(value ?? "")}',
              "                    </dd>",
              "                  </div>",
              "                ))}",
              "              </dl>",
              "              <button",
              "                onClick={() => handleCopyJson(img.metadata)}",
              '                className="mt-2 text-xs px-3 py-1 rounded bg-border hover:bg-border-hover transition-colors"',
              "              >",
              "                Copy JSON",
              "              </button>",
              "            </div>",
              "          )}",
              "        </div>",
              "      ))}",
              "    </div>",
              "  );",
              "}",
            ].join("\n"),
            message: "Integrate CopyButton into ImageGallery",
          },
        ],
        expect: {
          review: "APPROVE",
          merge: true,
          addLabels: ["approved"],
          removeLabels: ["in-review"],
        },
      },
    ],
  },
  {
    name: "pr-requested-changes",
    turns: [
      {
        title: "Refactor the image generation module",
        body: vagueIssueBody,
        initialLabels: ["in-review"],
        commitFile: {
          path: "src/components/Placeholder.tsx",
          content: "export default function Placeholder() { return null; }\n",
          message: "Add placeholder component",
        },
        expect: {
          review: "REQUEST_CHANGES",
          addLabels: ["changes-requested"],
          removeLabels: ["in-review"],
          comment: true,
        },
      },
    ],
  },
  {
    name: "merge-conflict-escalates",
    turns: [
      {
        title: "Add copy-to-clipboard button to gallery images",
        body: clearIssueBody,
        initialLabels: ["in-review"],
        createConflict: true,
        commitFile: {
          path: "src/lib/conflict-test.ts",
          content: "export const conflictTest = () => true;\n",
          message: "Add conflict test file",
        },
        expect: {
          review: "APPROVE",
          addLabels: ["human-review"],
          removeLabels: ["in-review"],
          comment: true,
        },
      },
    ],
  },
  {
    name: "no-valid-pr-number",
    turns: [
      {
        title: "Add copy-to-clipboard button to gallery images",
        body: clearIssueBody,
        initialLabels: ["ready"],
        expect: {
          noop: true,
        },
      },
    ],
  },
];
